name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: lint 
        run: make lint

  linux:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - run: make install
    - run: make installcheck

  macos:
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@v2
    - run: make install

    # The macOS environment should already have `brew` installed
    - name: make brew 
      run: |
        # Without this, `brew bundle` will fail on the Node.js preinstalled in the virtual environment
        brew unlink node@12
        make brew

    - run: make npm
    - run: make conda
    - run: make installcheck
